# Generated by Django 4.1.7 on 2023-09-11 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('minor_asset', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='id_UserAgent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.useragent'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='id_code_panne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_asset.codepanne'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='id_inventaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_asset.inventory'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='id_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_asset.machine'),
        ),
        migrations.AddField(
            model_name='team',
            name='assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assisted_teams', to='minor_asset.agent'),
        ),
        migrations.AddField(
            model_name='team',
            name='id_UserAgent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.useragent'),
        ),
        migrations.AddField(
            model_name='team',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_teams', to='minor_asset.agent'),
        ),
        migrations.AddField(
            model_name='remind',
            name='id_UserAgent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.useragent'),
        ),
        migrations.AddField(
            model_name='remind',
            name='id_planifierMaintenance',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='minor_asset.planifiermaintenance'),
        ),
        migrations.AddField(
            model_name='remind',
            name='id_planifierRepair',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='minor_asset.planifierrepair'),
        ),
        migrations.AddField(
            model_name='remind',
            name='id_planifierTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minor_asset.planifierteam'),
        ),
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_asset.adresse'),
        ),
        migrations.AddField(
            model_name='provider',
            name='id_UserAgent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.useragent'),
        ),
        migrations.AddField(
            model_name='planifierteam',
            name='id_UserAgent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.useragent'),
        ),
        migrations.AddField(
            model_name='planifierteam',
            name='id_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_asset.team'),
        ),
        migrations.AddField(
            model_name='planifierrepair',
            name='id_UserAgent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.useragent'),
        ),
        migrations.AddField(
            model_name='planifierrepair',
            name='id_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_asset.machine'),
        ),
        migrations.AddField(
            model_name='planifiermaintenance',
            name='id_UserAgent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.useragent'),
        ),
        migrations.AddField(
            model_name='planifiermaintenance',
            name='id_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_asset.machine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_asset.categoriemachine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='id_UserAgent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.useragent'),
        ),
        migrations.AddField(
            model_name='inventoryout',
            name='id_UserAgent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.useragent'),
        ),
        migrations.AddField(
            model_name='inventoryout',
            name='id_agent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='minor_asset.agent'),
        ),
        migrations.AddField(
            model_name='inventoryout',
            name='id_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_asset.inventory'),
        ),
        migrations.AddField(
            model_name='inventoryout',
            name='id_team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='minor_asset.team'),
        ),
        migrations.AddField(
            model_name='inventoryinto',
            name='id_UserAgent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.useragent'),
        ),
        migrations.AddField(
            model_name='inventoryinto',
            name='id_article',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='minor_asset.inventory'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='id_UserAgent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.useragent'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='id_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='minor_asset.categoryinventory'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='id_provider',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='minor_asset.provider'),
        ),
        migrations.AddField(
            model_name='diagnostics',
            name='id_UserAgent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.useragent'),
        ),
        migrations.AddField(
            model_name='diagnostics',
            name='id_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_asset.machine'),
        ),
        migrations.AddField(
            model_name='diagnostics',
            name='id_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_asset.team'),
        ),
        migrations.AddField(
            model_name='diagnostics',
            name='id_work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_asset.workorder'),
        ),
        migrations.AddField(
            model_name='codepanne',
            name='id_UserAgent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.useragent'),
        ),
        migrations.AddField(
            model_name='codepanne',
            name='id_categorie_panne',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='minor_asset.categoriepanne'),
        ),
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='minor_asset.adresse'),
        ),
        migrations.AddField(
            model_name='client',
            name='asset_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_asset.machine'),
        ),
        migrations.AddField(
            model_name='client',
            name='id_UserAgent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.useragent'),
        ),
        migrations.AddField(
            model_name='categoriepanne',
            name='id_UserAgent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.useragent'),
        ),
        migrations.AddField(
            model_name='categoriemachine',
            name='id_UserAgent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.useragent'),
        ),
        migrations.AddField(
            model_name='agent',
            name='adresse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='minor_asset.adresse'),
        ),
        migrations.AddField(
            model_name='agent',
            name='id_UserAgent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.useragent'),
        ),
    ]
