# Generated by Django 4.1.7 on 2023-09-29 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Agent', to='minor_asset.team'),
            preserve_default=False,
        ),
    ]
