# Generated by Django 4.1.7 on 2023-09-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='id_UserAgent',
        ),
        migrations.RemoveField(
            model_name='categoriemachine',
            name='id_UserAgent',
        ),
        migrations.RemoveField(
            model_name='categoriepanne',
            name='id_UserAgent',
        ),
        migrations.RemoveField(
            model_name='codepanne',
            name='id_UserAgent',
        ),
        migrations.RemoveField(
            model_name='diagnostics',
            name='id_UserAgent',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='id_UserAgent',
        ),
        migrations.RemoveField(
            model_name='inventoryinto',
            name='id_UserAgent',
        ),
        migrations.RemoveField(
            model_name='inventoryout',
            name='id_UserAgent',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='id_UserAgent',
        ),
        migrations.RemoveField(
            model_name='planifiermaintenance',
            name='id_UserAgent',
        ),
        migrations.RemoveField(
            model_name='planifierrepair',
            name='id_UserAgent',
        ),
        migrations.RemoveField(
            model_name='planifierteam',
            name='id_UserAgent',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='id_UserAgent',
        ),
        migrations.RemoveField(
            model_name='remind',
            name='id_UserAgent',
        ),
        migrations.RemoveField(
            model_name='team',
            name='id_UserAgent',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='id_UserAgent',
        ),
    ]
