# Generated by Django 4.1.7 on 2023-09-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0003_remove_agent_id_useragent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='phone1',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='phone2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='provider',
            name='web_site',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
