# Generated by Django 4.1.7 on 2023-09-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0004_provider_email_provider_phone1_provider_phone2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryinventory',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryinventory',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='categoryinventory',
            name='time_created',
            field=models.TimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryinventory',
            name='time_modified',
            field=models.TimeField(auto_now=True),
        ),
    ]
