# Generated by Django 4.1.7 on 2023-10-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0004_inventoryinto_user_inventoryout_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='immatriculation',
            field=models.CharField(blank=True, default='no immatriculation', max_length=20, null=True),
        ),
    ]
