# Generated by Django 4.1.7 on 2023-10-07 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0005_machine_immatriculation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inventoryinto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inventoryout',
            name='user',
        ),
    ]
