# Generated by Django 4.1.7 on 2023-09-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0005_categoryinventory_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryinventory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
