# Generated by Django 4.1.7 on 2023-09-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0006_categoryinventory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryinventory',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='categoryinventory',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='categoryinventory',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='categoryinventory',
            name='time_modified',
        ),
    ]
