# Generated by Django 4.1.7 on 2023-09-19 14:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0008_remove_agent_adresse_remove_client_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('time_modified', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='location',
        ),
        migrations.AddField(
            model_name='categoryinventory',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='categoryinventory',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='categoryinventory',
            name='time_created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='categoryinventory',
            name='time_modified',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryinventory',
            name='id_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minor_asset.location'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='id_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minor_asset.location'),
        ),
    ]
