# Generated by Django 4.1.7 on 2023-10-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0009_remove_codepanne_nom_codepanne_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='id_inventaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minor_asset.inventory'),
        ),
    ]
