# Generated by Django 4.1.7 on 2023-10-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0011_diagnostics_capacity_diagnostics_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostics',
            name='Brake_fuite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
