# Generated by Django 4.1.7 on 2023-10-11 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0014_alter_diagnostics_comment_alter_diagnostics_roster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryout',
            name='id_inventory_into',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.inventoryinto'),
        ),
    ]
