# Generated by Django 4.1.7 on 2023-10-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0015_inventoryout_id_inventory_into'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryout',
            name='id_agent',
        ),
    ]
