# Generated by Django 4.1.7 on 2023-10-12 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_agent_email_alter_team_name'),
        ('minor_asset', '0016_remove_inventoryout_id_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryout',
            name='id_article',
        ),
        migrations.AddField(
            model_name='inventoryout',
            name='id_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.agent'),
        ),
    ]
