# Generated by Django 4.1.7 on 2023-10-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0018_trackingpieces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingpieces',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='trackingpieces',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='trackingpieces',
            name='unit',
        ),
        migrations.AlterField(
            model_name='trackingpieces',
            name='id_inventory_out',
            field=models.ManyToManyField(to='minor_asset.inventoryout'),
        ),
    ]
