# Generated by Django 4.1.7 on 2023-10-13 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0019_remove_trackingpieces_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planifiermaintenance',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planifiermaintenance',
            name='date_of_taking_action',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
