# Generated by Django 4.1.7 on 2023-10-13 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0020_planifiermaintenance_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planifiermaintenance',
            name='time_of_taking_action',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planifiermaintenance',
            name='date_of_taking_action',
            field=models.DateField(),
        ),
    ]
