# Generated by Django 4.1.7 on 2023-10-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0021_planifiermaintenance_time_of_taking_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remind',
            name='id_planifierTeam',
        ),
    ]
