# Generated by Django 4.1.7 on 2023-10-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0022_remove_remind_id_planifierteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remind',
            name='id_planifierRepair',
        ),
    ]
