# Generated by Django 4.1.7 on 2023-10-19 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0025_remind_id_planifierrepair_remind_id_planifierteam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planifierrepair',
            old_name='priorite',
            new_name='priority',
        ),
        migrations.RemoveField(
            model_name='planifierrepair',
            name='comments',
        ),
        migrations.AddField(
            model_name='planifierrepair',
            name='time_of_taking_action',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planifierteam',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planifierteam',
            name='date_of_taking_action',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planifierteam',
            name='time_of_taking_action',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planifierrepair',
            name='action',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='planifierrepair',
            name='breakdown_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planifierrepair',
            name='date_of_taking_action',
            field=models.DateField(),
        ),
    ]
