# Generated by Django 4.1.7 on 2023-10-19 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0026_rename_priorite_planifierrepair_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remind',
            name='id_PlanifierRepair',
        ),
        migrations.RemoveField(
            model_name='remind',
            name='id_PlanifierTeam',
        ),
        migrations.RemoveField(
            model_name='remind',
            name='isPlanifierMaintenance',
        ),
        migrations.RemoveField(
            model_name='remind',
            name='isPlanifierRepair',
        ),
        migrations.RemoveField(
            model_name='remind',
            name='isPlanifierTeam',
        ),
        migrations.CreateModel(
            name='RemindTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_remind', models.DateTimeField(blank=True, null=True)),
                ('day', models.CharField(blank=True, max_length=100, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('time_modified', models.TimeField(auto_now=True)),
                ('id_PlanifierTeam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.planifierteam')),
            ],
        ),
        migrations.CreateModel(
            name='RemindRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_remind', models.DateTimeField(blank=True, null=True)),
                ('day', models.CharField(blank=True, max_length=100, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('time_modified', models.TimeField(auto_now=True)),
                ('id_PlanifierRepair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.planifierrepair')),
            ],
        ),
    ]
