# Generated by Django 4.1.7 on 2023-10-20 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0027_remove_remind_id_planifierrepair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planifierrepair',
            name='target_running_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planifierrepair',
            name='target_running_date',
            field=models.DateField(),
        ),
    ]
