# Generated by Django 4.1.7 on 2023-10-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0028_planifierrepair_target_running_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remindrepair',
            name='id_PlanifierRepair',
        ),
        migrations.DeleteModel(
            name='PlanifierRepair',
        ),
    ]
