# Generated by Django 4.1.7 on 2023-10-20 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0029_remove_remindrepair_id_planifierrepair_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanifierRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_taking_action', models.DateField()),
                ('time_of_taking_action', models.TimeField()),
                ('breakdown_description', models.TextField(blank=True, null=True)),
                ('action', models.CharField(max_length=500)),
                ('target_running_date', models.DateField()),
                ('target_running_time', models.TimeField()),
                ('priority', models.CharField(blank=True, choices=[('haut', 'Haut'), ('normal', 'Normal'), ('basse', 'Basse')], max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('time_modified', models.TimeField(auto_now=True)),
                ('id_machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.machine')),
            ],
        ),
        migrations.AddField(
            model_name='remindrepair',
            name='id_PlanifierRepair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.planifierrepair'),
        ),
    ]
