# Generated by Django 4.2.6 on 2023-10-24 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0032_diagnostics_isdiagnostic_diagnostics_ismaintenance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostics',
            name='isMaintenance',
        ),
    ]
