# Generated by Django 4.2.6 on 2023-10-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0033_remove_diagnostics_ismaintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='id_code_panne',
        ),
        migrations.AddField(
            model_name='workorder',
            name='id_code_panne',
            field=models.ManyToManyField(to='minor_asset.codepanne'),
        ),
    ]
