# Generated by Django 4.2.6 on 2023-10-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0034_remove_workorder_id_code_panne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryout',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
