# Generated by Django 4.2.6 on 2023-10-28 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0036_inventory_currency_used_by_entreprise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='asset_code',
            new_name='id_machine',
        ),
    ]
