# Generated by Django 4.2.6 on 2023-10-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0039_alter_inventory_capacity_alter_inventory_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryinto',
            old_name='id_article',
            new_name='i_article',
        ),
    ]
