# Generated by Django 4.2.6 on 2023-10-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0040_rename_id_article_inventoryinto_i_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryinto',
            old_name='i_article',
            new_name='id_article',
        ),
    ]
