# Generated by Django 4.2.6 on 2023-10-30 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_agent_email_alter_team_name'),
        ('minor_asset', '0042_alter_inventoryinto_id_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryinto',
            name='id_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.team'),
        ),
    ]
