# Generated by Django 4.2.6 on 2023-10-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0043_inventoryinto_id_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='designation',
            new_name='esignation',
        ),
    ]
