# Generated by Django 4.2.6 on 2023-10-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0044_rename_designation_inventory_esignation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='esignation',
            new_name='designation',
        ),
    ]
