# Generated by Django 4.2.7 on 2023-11-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0046_planifierteam_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindteam',
            name='hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
