# Generated by Django 4.2.7 on 2023-11-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0048_setting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
