# Generated by Django 4.2.7 on 2024-02-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0050_inventoryinto_price_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryinto',
            name='numbres_of_pieces',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
