# Generated by Django 4.2.7 on 2024-02-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0051_inventoryinto_numbres_of_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='numbres_of_pieces',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
