# Generated by Django 4.2.7 on 2024-02-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0052_inventory_numbres_of_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryinto',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
