# Generated by Django 4.2.7 on 2024-02-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0054_alter_diagnostics_cooling_alter_diagnostics_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryinto',
            name='price_unit_used_by_entreprise',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryinto',
            name='price_used_by_entreprise',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
