# Generated by Django 4.2.7 on 2024-02-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0055_alter_inventoryinto_price_unit_used_by_entreprise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryinto',
            name='numbres_of_pieces',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
