# Generated by Django 4.2.7 on 2024-03-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0056_alter_inventoryinto_numbres_of_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingpieces',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='trackingpieces',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trackingpieces',
            name='numbres_of_pieces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingpieces',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='trackingpieces',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trackingpieces',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='numbres_of_pieces',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
