# Generated by Django 4.2.7 on 2024-03-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0057_trackingpieces_capacity_trackingpieces_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryinto',
            name='byCapacity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryinto',
            name='byNumbreOfpieceç',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryinto',
            name='byWeight',
            field=models.BooleanField(default=False),
        ),
    ]
