# Generated by Django 4.2.7 on 2024-03-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0058_inventoryinto_bycapacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryinto',
            old_name='byNumbreOfpieceç',
            new_name='byNumbreOfpiece',
        ),
    ]
