# Generated by Django 4.2.7 on 2024-03-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0059_rename_bynumbreofpieceç_inventoryinto_bynumbreofpiece'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryinto',
            name='byCapacity',
        ),
        migrations.RemoveField(
            model_name='inventoryinto',
            name='byNumbreOfpiece',
        ),
        migrations.RemoveField(
            model_name='inventoryinto',
            name='byWeight',
        ),
        migrations.AddField(
            model_name='inventory',
            name='byCapacity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='byNumbreOfpiece',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='byWeight',
            field=models.BooleanField(default=False),
        ),
    ]
