# Generated by Django 4.2.7 on 2024-03-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0060_remove_inventoryinto_bycapacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingpieces',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
