# Generated by Django 4.2.7 on 2024-04-05 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0062_rename_quantity_trackingpieces_quantity_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostics',
            name='id_work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_asset.workorder'),
        ),
        migrations.AlterField(
            model_name='trackingpieces',
            name='id_work_order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='minor_asset.workorder', unique=True),
            preserve_default=False,
        ),
    ]
