# Generated by Django 4.2.7 on 2024-04-05 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0063_alter_diagnostics_id_work_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingpieces',
            name='id_work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='minor_asset.workorder'),
        ),
    ]
