# Generated by Django 4.2.7 on 2024-04-05 01:53

from django.db import migrations, models
import minor_asset.models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0064_alter_trackingpieces_id_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='work_order',
            field=models.CharField(default=minor_asset.models.generate_work_order, max_length=20, primary_key=True, serialize=False),
        ),
    ]
