# Generated by Django 4.2.7 on 2024-04-05 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0065_alter_workorder_work_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingpieces',
            name='id_inventory_out',
        ),
        migrations.AlterField(
            model_name='trackingpieces',
            name='id_work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor_asset.workorder'),
        ),
        migrations.AddField(
            model_name='trackingpieces',
            name='id_inventory_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.inventoryout'),
        ),
    ]
