# Generated by Django 4.2.7 on 2024-04-05 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0066_remove_trackingpieces_id_inventory_out_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingpieces',
            name='quantity_total',
        ),
    ]
