# Generated by Django 4.2.7 on 2024-04-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0067_remove_trackingpieces_quantity_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingpieces',
            name='quantity_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
