# Generated by Django 4.2.7 on 2024-04-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0068_trackingpieces_quantity_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingpieces',
            name='id_inventory_out',
        ),
    ]
