# Generated by Django 4.2.7 on 2024-04-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0070_trackingpieces_id_inventory_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryout',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
