# Generated by Django 4.2.7 on 2024-05-27 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_organisation_agent_entreprise_team_entreprise_and_more'),
        ('minor_asset', '0072_rename_user_inventoryinto_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindteam',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remindteam',
            name='entreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organisation'),
        ),
    ]
