# Generated by Django 4.2.7 on 2024-08-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0073_remindteam_createdby_remindteam_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='provider',
            name='web_site',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
