# Generated by Django 4.1.7 on 2023-10-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('team_type', models.CharField(choices=[('MAINTENANCE', 'MAINTENANCE'), ('INVENTAIRE', 'INVENTAIRE'), ('OTHERS', 'OTHERS')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('time_modified', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('postnom', models.CharField(max_length=250)),
                ('matricule', models.CharField(max_length=10, unique=True)),
                ('phone1', models.CharField(max_length=10)),
                ('phone2', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rue', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('quarter', models.CharField(blank=True, max_length=150, null=True)),
                ('commune', models.CharField(blank=True, max_length=150, null=True)),
                ('ville', models.CharField(blank=True, max_length=50, null=True)),
                ('pays', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('isSupervisor', models.BooleanField(default=False)),
                ('isAssistant', models.BooleanField(default=False)),
                ('isAgent', models.BooleanField(default=True)),
                ('user_apps_type', models.CharField(choices=[('ASSET', 'ASSET'), ('FLEET', 'FLEET')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('time_modified', models.TimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='users.team')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='agent',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.agent'),
            preserve_default=False,
        ),
    ]
