# Generated by Django 4.2.7 on 2024-03-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_agent_email_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('MAINTENANCE', 'MAINTENANCE'), ('INVENTAIRE', 'INVENTAIRE'), ('CONTROLEUR', 'CONTROLEUR'), ('OTHERS', 'OTHERS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='profil',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('INVENTORY', 'INVENTORY'), ('MAINTENANCE', 'MAINTENANCE'), ('CONTROLEUR', 'CONTROLEUR')], max_length=20, null=True),
        ),
    ]
