# Generated by Django 4.2.7 on 2024-04-22 19:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_team_team_type_alter_user_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('MINOR', 'MINOR'), ('MECANIQUE', 'MECANIQUE')], max_length=250)),
                ('trial', models.BooleanField()),
                ('on_paid', models.BooleanField()),
                ('date_to_paid', models.DateTimeField()),
                ('data_until_paid', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('time_modified', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='entreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organisation'),
        ),
        migrations.AddField(
            model_name='team',
            name='entreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organisation'),
        ),
        migrations.AddField(
            model_name='user',
            name='entreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organisation'),
        ),
    ]
