# Generated by Django 4.2.7 on 2024-08-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_organisation_agent_entreprise_team_entreprise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
