# Generated by Django 4.2.7 on 2023-11-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
            ],
        ),
    ]
