# Generated by Django 4.2.7 on 2023-11-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='capacity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
