# Generated by Django 4.2.7 on 2024-02-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_dash', '0002_alter_setting_capacity_alter_setting_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='distance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
