# Generated by Django 4.2.7 on 2024-04-25 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_organisation_agent_entreprise_team_entreprise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minor_dash', '0003_setting_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='setting',
            name='entreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organisation'),
        ),
    ]
