# Generated by Django 4.2.7 on 2024-08-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_dash', '0004_setting_createdby_setting_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='capacity',
            field=models.CharField(blank=True, default='Litre (L)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='currency',
            field=models.CharField(blank=True, default='CDF', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='distance',
            field=models.CharField(blank=True, default='Kilometer(km)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='weight',
            field=models.CharField(blank=True, default='Kilogram (kg)', max_length=20, null=True),
        ),
    ]
