# Generated by Django 4.1.7 on 2023-10-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0008_alter_diagnostics_id_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codepanne',
            name='nom',
        ),
        migrations.AddField(
            model_name='codepanne',
            name='code',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoriemachine',
            name='nom',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='categoriepanne',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone1',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone2',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone1',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone2',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='web_site',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
