# Generated by Django 4.1.7 on 2023-10-09 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_agent_email_alter_team_name'),
        ('minor_asset', '0010_alter_workorder_id_inventaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostics',
            name='capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnostics',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnostics',
            name='distance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnostics',
            name='poids',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categoryinventory',
            name='id_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.location'),
        ),
        migrations.AlterField(
            model_name='client',
            name='asset_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.machine'),
        ),
        migrations.AlterField(
            model_name='codepanne',
            name='id_categorie_panne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.categoriepanne'),
        ),
        migrations.AlterField(
            model_name='diagnostics',
            name='id_machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.machine'),
        ),
        migrations.AlterField(
            model_name='diagnostics',
            name='id_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.team'),
        ),
        migrations.AlterField(
            model_name='diagnostics',
            name='id_work_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.workorder'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.categoryinventory'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.location'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.provider'),
        ),
        migrations.AlterField(
            model_name='inventoryinto',
            name='id_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.inventory'),
        ),
        migrations.AlterField(
            model_name='inventoryout',
            name='id_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.agent'),
        ),
        migrations.AlterField(
            model_name='inventoryout',
            name='id_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.inventory'),
        ),
        migrations.AlterField(
            model_name='inventoryout',
            name='id_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.team'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.categoriemachine'),
        ),
        migrations.AlterField(
            model_name='planifiermaintenance',
            name='id_machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.machine'),
        ),
        migrations.AlterField(
            model_name='planifierrepair',
            name='id_machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.machine'),
        ),
        migrations.AlterField(
            model_name='planifierteam',
            name='id_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.team'),
        ),
        migrations.AlterField(
            model_name='remind',
            name='id_planifierMaintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.planifiermaintenance'),
        ),
        migrations.AlterField(
            model_name='remind',
            name='id_planifierRepair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.planifierrepair'),
        ),
        migrations.AlterField(
            model_name='remind',
            name='id_planifierTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.planifierteam'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='id_code_panne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.codepanne'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='id_inventaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.inventory'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='id_machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.machine'),
        ),
    ]
