# Generated by Django 4.1.7 on 2023-10-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0013_alter_diagnostics_end_repair_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostics',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostics',
            name='roster',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostics',
            name='time_decimal_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
