# Generated by Django 4.1.7 on 2023-10-12 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0017_remove_inventoryout_id_article_inventoryout_id_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingPieces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('time_modified', models.TimeField(auto_now=True)),
                ('id_inventory_out', models.ManyToManyField(null=True, to='minor_asset.inventoryout')),
                ('id_machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.machine')),
                ('id_work_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.workorder')),
            ],
        ),
    ]
