# Generated by Django 4.1.7 on 2023-10-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0024_alter_remind_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='remind',
            name='id_PlanifierRepair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.planifierrepair'),
        ),
        migrations.AddField(
            model_name='remind',
            name='id_PlanifierTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.planifierteam'),
        ),
        migrations.AddField(
            model_name='remind',
            name='isPlanifierMaintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remind',
            name='isPlanifierRepair',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remind',
            name='isPlanifierTeam',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='remind',
            name='id_planifierMaintenance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='minor_asset.planifiermaintenance'),
        ),
    ]
