# Generated by Django 4.1.7 on 2023-10-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0030_planifierrepair_remindrepair_id_planifierrepair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planifierrepair',
            name='target_running_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planifierrepair',
            name='target_running_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
