# Generated by Django 4.2.6 on 2023-10-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0031_alter_planifierrepair_target_running_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostics',
            name='isDiagnostic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnostics',
            name='isMaintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnostics',
            name='isRepair',
            field=models.BooleanField(default=False),
        ),
    ]
