# Generated by Django 4.2.7 on 2023-11-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor_asset', '0045_rename_esignation_inventory_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='planifierteam',
            name='day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
